name: Wheels

on:
  push:
    branches:
    - master
  release:
    types:
    - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Build sdist
        if: matrix.os == 'windows-2019'
        run: |
          pip install scikit-build cython
          python setup.py sdist

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cibuildwheel==2.3.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: 'pp*'
          CIBW_BEFORE_BUILD: |
            if exist _skbuild rmdir /s /q _skbuild

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*

  upload_release:
    name: Upload release
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
