[tool.poetry]
name = "coregeist"
version = "0.1.3"
description = "coregeist is a Python library to convert deep neural network models into c source code."
authors = ["germar <g.schlegel@geisten.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.12"
torch = "^1.10.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = "^21.12-beta.0"
flake8 = "^4.0.1"
mypy = "^0.931"
bandit = "^1.7.1"
pytest = "^6.2.5"
autoflake = "^1.4"
autopep8 = "^1.6.0"
pytest-cov = "^3.0.0"
torchvision = "^0.11.0"
matplotlib = "^3.5.1"
timm = "^0.4.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

