[tool.poetry]
authors = ["kexue <xana278@foxmail.com>"]
description = ""
license = "MIT"
name = "nonebot-plugin-tvseries"
readme = "README.md"
version = "0.0.2.3"

[tool.poetry.dependencies]
lxml = "^4.6.4"
nonebot-adapter-onebot = "2.0.0-beta.1"
nonebot-plugin-htmlrender = {version = "^0.0.4.2", source = "aliyun"}
nonebot2 = "2.0.0-beta.1"
python = "^3.9"
httpx = "^0.21.3"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pillow = "^8.4.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
