[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires = ["setuptools~=57.0.0", "setuptools_scm[toml]>=5", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# See configuration details in https://github.com/pypa/setuptools_scm
local_scheme = "no-local-version"
# local_scheme = "no-local-version"
# version_scheme = "no-guess-dev"
# version_scheme = "python-simplified-semver"

