[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=60.8.1", "wheel","urllib3>=1.26.8","asyncio>=3.4.3"]
build-backend = "setuptools.build_meta"
