[tool.poetry]
name = "security_poc"
version = "5.8.0"
description = "Just to test some security things"
authors = ["Marco Dennstädt <Marco.Dennstaedt@zuehlke.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
