[tool.towncrier]
    package = "mopidy_funkwhale"
    directory = ".changelog"
    filename = "CHANGELOG.md"
    all_bullets = true
    template = ".changelog/changes/template.md"
    start_string = "# Changelog\n"
    issue_format = "[#{issue}](https://dev.funkwhale.audio/funkwhale/mopidy/-/issues/{issue})"
    underlines = ["", ""]
    title_format = "## {version} ({project_date})\n"

