[tool.poetry]
name = "a28"
version = "1.1.0"
description = "A set of resources and tools to help developers create packages for the Area28 application."
authors = ["Area28 Technologies <dev@area28.io>"]
license = "MIT"
readme = "README.md"
homepage = "https://area28.io"
include = ["CHANGELOG.md", "LICENSE", "README.md", "docs", "tests"]
packages = [{ include = "a28", from = "src" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Environment :: Console :: Curses",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: Developers"
]

[tool.poetry.dependencies]
python = ">=3.7, <4"
requests = "^2.23.0"
coloredlogs = { version = ">=14.0", extras = ["color"] }
certifi = "^2021.10.8"

[tool.poetry.dev-dependencies]
bandit = "^1.6.3"
flakehell = "^0.9.0"
pytest = "^6.2"
pycodestyle = "^2.0.1"
flake8-2020 = "^1.6.0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.4.3"
flake8-builtins = "^1.5.3"
flake8-cognitive-complexity = "^0.1.0"
flake8-comprehensions = "^3.5.0"
flake8-eradicate = "^1.0.0"
flake8-fixme = "^1.1.1"
flake8-functions = "^0.0.6"
flake8-isort = "^4.0.0"
flake8-ownership = "^2.0.1"
flake8-pytest = "^1.3"
flake8-simplify = "^0.14.0"
flake8-variables-names = "^0.0.4"
flake8-docstrings = "^1.6.0"
flake8-debugger = "^4.0.0"
flake8-quotes = "^3.3.1"
flake8-typing-imports = "^1.10.0"
mccabe = "^0.6.1"
pep8-naming = "^0.11.1"
pyflakes = "^2.3.1"
pylint = "^2.8.2"
Sphinx = "^4.0.1"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "^0.5.2"
flake8-alfred = "^1.1.1"
mypy-extensions = "^0.4.3"
poetry-dynamic-versioning = "^0.12.6"
MarkupSafe = "^1.1.1"
auto-changelog = "^0.5.3"
pytest-cov = "^2.12.1"
gitlint = "^0.15.1"
responses = "^0.15.0"
coverage = { version = "^6.1.1", extras = ["toml"] }

[tool.poetry.scripts]
a28 = "a28.cli:main"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
metadata = false
latest-tag = true
bump = true
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
files = ["src/a28/__init__.py"]

[tool.flakehell]
extended_default_ignore = []
format = 'grouped'
max_line_length = 100
max_complexity = 6
show_source = true
exclude = [".git", "__pycache__", "docs", "build", "tests", "dist", ".venv", ".pytest_cache", "htmlcov"]

[tool.flakehell.plugins]
pycodestyle = ["+*"]
pyflakes = ["+*"]
"flake8-*" = ["+*"]
pylint = ["+*"]
pep8-naming = ["+*"]
mccabe = ["+*"]

[tool.pylint."MESSAGES CONTROL"]
enable = "all"

[tool.isort]
line_length = 100
combine_as_imports = true
balanced_wrapping = true
lines_after_imports = 2
lines_between_sections = -1
include_trailing_comma = false
multi_line_output = 2
color_output = true

[build-system]
requires = ["poetry-core>=1.0.4", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ['src']
