name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -mpip install --upgrade pip wheel pytest pytest-cov
        case '${{ matrix.python-version }}' in
        3.6)
          pip install ipython==4.1.0;;
        3.10)
          ;;
        *)
          exit 1;;
        esac
        python -mpip install .
    - name: Test
      run: |
        pyver="$(python -c 'import sys; print("{0.major}.{0.minor}".format(sys.version_info))')" &&
        COVERAGE_FILE=".coverage.$pyver" python -mpytest --cov --cov-branch
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: .coverage.*

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Download coverage
      uses: actions/download-artifact@v2
      with:
        name: coverage
    - name: Coverage
      run: |
        python -mpip install --upgrade coverage &&
        python -mcoverage combine .coverage.* &&  # Unifies paths across envs.
        python -mcoverage report --show-missing
