# Generated by Django 2.2.16 on 2020-11-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0004_auto_20201103_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='exposition archivée'),
        ),
    ]
