# Generated by Django 2.2.16 on 2020-11-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0008_auto_20201105_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public',
            old_name='public',
            new_name='name',
        ),
    ]
