# Generated by Django 2.2.16 on 2020-11-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0009_auto_20201110_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='condition',
            new_name='name',
        ),
    ]
