# Generated by Django 2.2.16 on 2020-12-02 10:23

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('djangoldp_exposition', '0017_auto_20201127_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structuremateriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nom de la structure')),
            ],
        ),
        migrations.RenameModel(
            old_name='Structure',
            new_name='Structureexpo',
        ),
        migrations.AlterField(
            model_name='materiel',
            name='structure',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_exposition.Structuremateriel', verbose_name='Structure'),
        ),
    ]
