name: graphgenerator
channels:
  - conda-forge
  - defaults
dependencies:
  - networkx=2.6.3
  - pandas=1.3.5
  - pytz=2021.3
  - matplotlib=3.5.0
  - pip:
      - "--editable=git+https://github.com/JustAnotherArchivist/snscrape.git#egg=snscrape"
