[tool.poetry]
name = "eagerx_gui"
version = "0.1.1"
description = "GUI to visualise graphs in EAGERx."
authors = ["Jelle Luijkx <j.d.luijkx@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.6.2"
eagerx = "^0.1.0"
opencv-python = "4.3.0.36"
pyqtgraph = "^0.11.1"
PyQt5 = "^5.15.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.1.0"
eagerx = {path = "/home/bas/eagerx_dev/eagerx", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
