VERSION_YEAR = 2022
VERSION_MONTH = int('02')
VERSION_DAY = int('09')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('06')
MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 202202092106
version_date = '2022/02/09 21:06'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
