[tool.poetry]
name = "archimedes-python-client"
version = "3.3.2"
description = "The Python library for Archimedes"
authors = ["Optimeering AS <dev@optimeering.com>"]
license = "Apache-2.0"
packages = [{include = "archimedes"}]

[tool.poetry.dependencies]
python = ">=3.7.1,<4"
pandas = ">=1.0.5"
records = ">=0.5.3"
prefect = ">=0.14.0"
mlflow = ">=1.12.0"
psycopg2-binary = ">=2.8.6"
matplotlib = ">=3.2.2"
dynaconf = ">=3.1.2"
requests = ">=2"
simplejson = ">=2.6.1"
msal = ">=1.10.0,<2.0.0"
msal-extensions = "^0.3.1"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
coverage = "*"
black = "21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
