[project]
name = "newfile"
version = "0.1.0"
description = "create files from preset template cli app"
readme = "README.md"
authors = [
    { name = "teeaz", email = "teeaz@github.com" },
]
dependencies = [
    "lazyaml>=6.0.4",
    "click>=8.0.3",
]
requires-python = ">=3.9"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/teeaz/newfile"

[project.scripts]
new = "newfile.__main__:main"

[tool.pdm]

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"
