[tool.poetry]
name = "decision-segment"
version = "0.0.2"
description = "Separates decision segments"
authors = ["Marcelino G. Veloso III <mars@veloso.one>"]

[tool.poetry.dependencies]
python = "^3.9"
citation-decision = "^0.0.1"
decision-footnote = "^0.0.1"
decision-section = "^0.0.1"
decision-title = "^0.0.1"
statute-matcher = "^0.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.12.1"
mypy = "^0.930"
black = "^22.1"
isort = "^5.10.1"
pre-commit = "^2.17.0"
ipykernel = "^6.7.0"
tqdm = "^4.62"

[tool.pytest]
minversion = "6.0"
addopts = "-ra -q --cov=decision_segment tests/"
testpaths = ["tests"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = 'True'

[tool.black]
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''


[build-system]
requires = ["poetry-core>=1.1.7"]
build-backend = "poetry.core.masonry.api"
