[tool.poetry]
name = "pystringbio"
version = "0.1.1"
description = ""
authors = ["glaunay <pitooon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.65.1"
pydantic = "^1.8.2"
prompt-toolkit = "^3.0.18"
docopt = "^0.6.2"
uvicorn = "^0.13.4"
marshmallow = "^3.12.1"
requests = "^2.25.1"
pyrediscore = "^0.2.5"
progressbar2 = "^3.53.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "pystringbio.server:start"
