[tool.poetry]
name = "nr.util"
version = "0.5.0"
description = "General purpose Python utility library."
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
license = "MIT"
readme = "readme.md"
packages = [
  { include="nr/util", from="src" }
]

  [tool.poetry.dependencies]
  python = "^3.10"

  [tool.poetry.extras]
  config = ["databind.core ^1.3.2"]

  [tool.poetry.dev-dependencies]
  pytest = "^6.2.5"
  mypy = "^0.931"
  types-setuptools = "^57.4.9"

[tool.shut]

  [tool.shut.test]
  pytest = "pytest test/"
  mypy = "mypy src/ --namespace-packages"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
