
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-09T11:17:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e25ce59185c3318c25227d85784ffda255364d8",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
