[tool.poetry]
name = "freekassa"
version = "0.1.4"
description = "FreeKassa Api"
authors = ["odi1n"]
repository = 'https://github.com/odi1n/freekassa_api'
readme = 'README.md'
keywords = ['text']

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
