# Generated by Django 2.2.16 on 2020-11-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0003_auto_20201103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expo',
            name='associateddoc',
            field=models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Associateddoc', verbose_name='Doc associé'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='associatedlink',
            field=models.ManyToManyField(blank=True, max_length=150, to='djangoldp_exposition.Associatedlink', verbose_name='Lien associé'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='condition',
            field=models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Condition', verbose_name='Condition de prêt'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='contact',
            field=models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='illustration',
            field=models.ManyToManyField(blank=True, max_length=150, to='djangoldp_exposition.Illustration', verbose_name="Illustration de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='pedagogictool',
            field=models.ManyToManyField(blank=True, max_length=150, to='djangoldp_exposition.Pedagogictool', verbose_name='Outil pédagogique'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='presslink',
            field=models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Presslink', verbose_name='Revue de presse'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='promoteddoc',
            field=models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Promoteddoc', verbose_name='Document mis en avant'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='promotedlink',
            field=models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Promotedlink', verbose_name='Lien mis en avant'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='promotedvideo',
            field=models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Promotedvideo', verbose_name='Vidéo mise en avant'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='public',
            field=models.ManyToManyField(blank=True, max_length=150, to='djangoldp_exposition.Public', verbose_name='Public concerné'),
        ),
    ]
