# Generated by Django 2.2.16 on 2020-11-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0005_expo_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expo',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
