# Generated by Django 2.2.16 on 2020-11-05 14:17

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0006_auto_20201105_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la structure')),
                ('title', models.CharField(max_length=50, verbose_name='Nom du matériel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description des éléments')),
                ('withdrawaldate', models.DateField(blank=True, null=True, verbose_name='Date limite de retrait')),
                ('availabilitydate', models.DateField(blank=True, null=True, verbose_name='Date de mise à disposition')),
                ('location', models.CharField(max_length=150, verbose_name='Lieu de retrait')),
                ('modalite', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modalités')),
                ('condition', models.BooleanField(default=False, verbose_name='Condition de prêt')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Tarif')),
                ('archived', models.BooleanField(default=False, verbose_name='matériel archivé')),
                ('contact', models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Contact', verbose_name='Contact')),
                ('illustration', models.ManyToManyField(blank=True, max_length=150, to='djangoldp_exposition.Illustration', verbose_name='Illustration du matériel')),
                ('keyword', models.ManyToManyField(blank=True, to='djangoldp_exposition.Keyword')),
                ('promotedvideo', models.ManyToManyField(blank=True, max_length=50, to='djangoldp_exposition.Promotedvideo', verbose_name='Vidéo mise en avant')),
            ],
        ),
    ]
