# Generated by Django 2.2.16 on 2020-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0007_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expo',
            name='keyword',
            field=models.ManyToManyField(blank=True, to='djangoldp_exposition.Keyword', verbose_name='mot clé'),
        ),
    ]
