# Generated by Django 2.2.16 on 2020-11-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0010_auto_20201110_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name="Login de l'utilisateur"),
        ),
        migrations.AddField(
            model_name='materiel',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name="Login de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='exposition archivée'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name="Titre de l'exposition"),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='matériel archivé'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lieu de retrait'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom du matériel'),
        ),
    ]
