# Generated by Django 2.2.16 on 2020-11-18 09:00

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0011_auto_20201115_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matoscondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(max_length=50, verbose_name='Condition de prêt')),
            ],
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(max_length=50, verbose_name='Thématique')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='visiblity',
            new_name='visibility',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='price',
        ),
        migrations.AddField(
            model_name='expo',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='expo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='expo',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='city',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='pedagogictool',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Description courte de l'outil pédagogique"),
        ),
        migrations.AddField(
            model_name='pedagogictool',
            name='doc',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name="lien vers l'outil pédagogique"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de téléphone du contact'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='condition',
            field=models.ManyToManyField(max_length=50, to='djangoldp_exposition.Condition', verbose_name='Condition de prêt'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='description',
            field=models.TextField(verbose_name="Description succinte de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='descriptive',
            field=models.TextField(verbose_name="Descriptif du contenu de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='dimension',
            field=models.IntegerField(verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='illustration',
            field=models.ManyToManyField(max_length=150, to='djangoldp_exposition.Illustration', verbose_name="Illustration de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='productiondate',
            field=models.DateField(verbose_name='Date de production'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='public',
            field=models.ManyToManyField(max_length=150, to='djangoldp_exposition.Public', verbose_name='Public concerné'),
        ),
        migrations.RemoveField(
            model_name='expo',
            name='thematique',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='condition',
        ),
        migrations.AddField(
            model_name='expo',
            name='thematique',
            field=models.ManyToManyField(to='djangoldp_exposition.Thematique', verbose_name='Thématique'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='condition',
            field=models.ManyToManyField(max_length=50, to='djangoldp_exposition.Matoscondition', verbose_name='Condition de prêt'),
        ),
    ]
