# Generated by Django 2.2.16 on 2020-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0012_auto_20201118_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville'),
        ),
    ]
