# Generated by Django 2.2.16 on 2020-11-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0013_auto_20201119_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='condition',
        ),
        migrations.AddField(
            model_name='materiel',
            name='condition',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_exposition.Matoscondition', verbose_name='Condition de prêt'),
            preserve_default=False,
        ),
    ]
