# Generated by Django 2.2.16 on 2020-11-26 14:30

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0015_auto_20201123_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nom de la structure')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse')),
                ('postcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville')),
                ('lat', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Lattitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.RemoveField(
            model_name='expo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='expo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='expo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expo',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='postcode',
        ),
        migrations.AddField(
            model_name='expo',
            name='structure',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_exposition.Structure', verbose_name='Structure'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='structure',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_exposition.Structure', verbose_name='Structure'),
        ),
    ]
