# Generated by Django 2.2.16 on 2020-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0016_auto_20201126_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='address',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='city',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='postcode',
        ),
        migrations.AddField(
            model_name='expo',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='expo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='expo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Lattitude'),
        ),
        migrations.AddField(
            model_name='expo',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='expo',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Lattitude'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code postal'),
        ),
    ]
