# Generated by Django 2.2.16 on 2021-01-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_exposition', '0018_auto_20201202_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expo',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='exposition archivée'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='associateddoc',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Associateddoc', verbose_name='Doc associé'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='associatedlink',
            field=models.ManyToManyField(blank=True, max_length=150, null=True, to='djangoldp_exposition.Associatedlink', verbose_name='Lien associé'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='condition',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Condition', verbose_name='Condition de prêt'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='contact',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Description succinte de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='descriptive',
            field=models.TextField(blank=True, null=True, verbose_name="Descriptif du contenu de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='dimension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='illustration',
            field=models.ManyToManyField(blank=True, max_length=150, null=True, to='djangoldp_exposition.Illustration', verbose_name="Illustration de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='keyword',
            field=models.ManyToManyField(blank=True, null=True, to='djangoldp_exposition.Keyword', verbose_name='mot clé'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='pedagogictool',
            field=models.ManyToManyField(blank=True, max_length=150, null=True, to='djangoldp_exposition.Pedagogictool', verbose_name='Outil pédagogique'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='presslink',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Presslink', verbose_name='Revue de presse'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='productiondate',
            field=models.DateField(blank=True, null=True, verbose_name='Date de production'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='promoteddoc',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Promoteddoc', verbose_name='Document mis en avant'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='promotedlink',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Promotedlink', verbose_name='Lien mis en avant'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='promotedvideo',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Promotedvideo', verbose_name='Vidéo mise en avant'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='public',
            field=models.ManyToManyField(blank=True, max_length=150, null=True, to='djangoldp_exposition.Public', verbose_name='Public concerné'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='thematique',
            field=models.ManyToManyField(blank=True, null=True, to='djangoldp_exposition.Thematique', verbose_name='Thématique'),
        ),
        migrations.AlterField(
            model_name='expo',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Titre de l'exposition"),
        ),
        migrations.AlterField(
            model_name='expo',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Login de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='matériel archivé'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='condition',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoldp_exposition.Matoscondition', verbose_name='Condition de prêt'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='contact',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='illustration',
            field=models.ManyToManyField(blank=True, max_length=150, null=True, to='djangoldp_exposition.Illustration', verbose_name='Illustration du matériel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='keyword',
            field=models.ManyToManyField(blank=True, null=True, to='djangoldp_exposition.Keyword'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu de retrait'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='promotedvideo',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='djangoldp_exposition.Promotedvideo', verbose_name='Vidéo mise en avant'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom du matériel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Login de l'utilisateur"),
        ),
    ]
