name: Build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip cx_Freeze pytest
          pip install -r requirements.txt


      - name: Build with CxFreeze
        run: cxfreeze -c obs_manager/src/menu.py --target-dir app/app-${{ matrix.os }} --target-name Obsidian_Snippet_Manager

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: app/app-${{ matrix.os }}
          if-no-files-found: error
