[tool.poetry]
name = "equanpy"
version = "0.1.0"
description = "Python packaging data school"
authors = ["Didier SCHMITT <dschmitt@equancy.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
