
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-11T12:34:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5970673f4f6fb826bcde0fcd32867981c95f60ed",
 "version": "0.7.1.post.dev373"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
