name: PyTest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build package
        run:
          python -m pip install .
      - name: Run test suite
        run: |
          python -m pytest --benchmark-skip
