
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-09T17:29:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2e848b9199e85b283b9352e55fe85d6050adbcb",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
