name: Test

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["pypy-3.8", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          # Include new variables for Codecov
          - { codecov-flag: GHA_Ubuntu, os: ubuntu-latest }
          - { codecov-flag: GHA_macOS, os: macos-latest }
          - { codecov-flag: GHA_Windows, os: windows-latest }

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install gettext

      - name: Install macOS dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install gettext

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -U tox

      - name: Generate translation binaries
        run: |
          scripts/generate-translation-binaries.sh

      - name: Tox tests
        run: |
          tox -e py

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.codecov-flag }}
          name: ${{ matrix.os }} Python ${{ matrix.python-version }}
