"""
    traQ v3

    traQ v3 API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import traq
from traq.model.user_stats_stamp import UserStatsStamp


class TestUserStatsStamp(unittest.TestCase):
    """UserStatsStamp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserStatsStamp(self):
        """Test UserStatsStamp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserStatsStamp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
