"""
    traQ v3

    traQ v3 API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import traq
from traq.model.file_info_thumbnail import FileInfoThumbnail


class TestFileInfoThumbnail(unittest.TestCase):
    """FileInfoThumbnail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileInfoThumbnail(self):
        """Test FileInfoThumbnail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileInfoThumbnail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
