"""
    traQ v3

    traQ v3 API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import traq
from traq.model.patch_client_request import PatchClientRequest


class TestPatchClientRequest(unittest.TestCase):
    """PatchClientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchClientRequest(self):
        """Test PatchClientRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchClientRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
