"""
    traQ v3

    traQ v3 API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import traq
from traq.model.o_auth2_scope import OAuth2Scope


class TestOAuth2Scope(unittest.TestCase):
    """OAuth2Scope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2Scope(self):
        """Test OAuth2Scope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OAuth2Scope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
