"""
    traQ v3

    traQ v3 API  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import traq
from traq.model.o_auth2_scope import OAuth2Scope
globals()['OAuth2Scope'] = OAuth2Scope
from traq.model.o_auth2_client import OAuth2Client


class TestOAuth2Client(unittest.TestCase):
    """OAuth2Client unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2Client(self):
        """Test OAuth2Client"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OAuth2Client()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
