[dependencies.ms_toollib]
features = ["py"]
path = "local_dependencies/ms_toollib"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.15.1"

[lib]
crate-type = ["cdylib", "lib"]
name = "ms_toollib"

[package]
authors = ["Wang Jianing <wangjianing@88.com>"]
description = "Algorithms  for Minesweeper"
documentation = "https://docs.rs/ms_toollib/"
edition = "2018"
keywords = ["minesweeper", "possibility", "mine", "laymine"]
license = "MIT"
name = "ms_toollib"
readme = "README.md"
version = "1.2.11"
