image: paternal/pythons

tox:
  script:
    - tox
  coverage: '/^TOTAL.*\s(\d+)\%$/'

pages:
  script:
    - python3 -m pip install -r requirements.txt
    - test -d public || mkdir public
    - cp pypimonitor/data/static/* public/
    - python3 -m pypimonitor examples/spalax.yaml > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main
