from TkWebPage import*
def IE_test():
    I = IE(["baidu","pypi","game","bilibili"])
    I.url("baidu","http://www.baidu.com")
    I.url("pypi","http://pypi.org")
    I.url("game","http://chromedino.com")
    I.url("bilibili","http://www.bilibili.com")
    I.title("baidu","baidu")
    I.title("pypi","pypi")
    I.title("game","game")
    I.title("bilibili","bilibili")
    I.run("baidu")
    I.run("pypi")
    I.run("game")
    I.run("bilibili")
def HTML_test():
    H = HTML("html")
    H.title("html","HTML")
    H.run("html")
def Chromium_test():
    C = Chrome(["baidu","pypi","game","bilibili"])
    C.url("baidu","www.baidu.com")
    C.url("pypi","pypi.org")
    C.url("game","chromedino.com")
    C.url("bilibili","www.bilibili.com")
    C.title("baidu","baidu")
    C.title("pypi","pypi")
    C.title("game","game")
    C.title("bilibili","bilibili")
    C.run("baidu")
    C.run("pypi")
    C.run("game")
    C.run("bilibili")
if __name__ == "__main__":
    IE_test()
    HTML_test()
    Chromium_test()
