[tool.poetry]
name = "nacre"
version = "0.2.7"
description = "Nacre"
authors = ["Sidn <sidnvy@gmail.com>"]
include = [
    # Compiled extensions must be included in the wheel distributions
    { path = "nacre/**/*.so", format = "wheel" },
    { path = "nacre/**/*.pyd", format = "wheel" },
]

[tool.poetry.dependencies]
python = ">=3.8.11,<3.10"
aiohttp-socks = "^0.7.1"
grpcio = "^1.40.0"
aiokafka = "^0.7.2"
fastavro = "^1.4.6"
python-schema-registry-client = "^2.2.0"
nautilus-trader = "1.135.0"
prometheus-async = {extras = ["aiohttp"], version = "^19.2.0"}
fire = "^0.4.0"
tenacity = "^8.0.1"

[tool.poetry.dev-dependencies]
toml = "^0.10.2"
python-dotenv = {extras = ["cli"], version = "^0.19.0"}
setuptools = "^57.4.0"
grpcio-tools = "^1.40.0"

coverage = "4.5.4"  # Pinned at 4.5.4 due Cython 3.0.0a9
nox = "^2021.10.1"
pre-commit = "^2.16.0"
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-benchmark = "^3.4.1"
pytest-cov = "2.10.1"  # Pinned at 2.10.1 due coverage 4.5.4
pytest-mock = "^3.6.1"
pytest-xdist = { version = "2.5.0", extras = ["psutil"] }
numpydoc = { version = "^1.1.0", optional = true }
sphinx = { version = "^4.3.1", optional = true }
sphinx-rtd-theme = { version = "^1.0.0", optional = true }

[build-system]
requires = [
    "setuptools",
    "poetry-core>=1.0.7",
    "numpy>=1.21.5",
    "Cython>=3.0.0a9",
    "nautilus-trader~=1.135.0",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.poetry.scripts]
nacre = 'nacre.console.cli:run'
