[tool.poetry]
name = "statsbombpy"
version = "1.1.1"
description = ""
authors = ["Dinesh Vatvani <dr.mirpuri@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
joblib = "^1.0.1"
inflect = "^5.3.0"
nose2 = "^0.10.0"
pandas = "^1.3.2"
requests = "^2.26.0"
requests-cache = "^0.7.4"
ipykernel = "^6.2.0"
python-dotenv = "^0.19.0"
black = "^21.7b0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
