VERSION_YEAR = 2022
VERSION_MONTH = int('02')
VERSION_DAY = int('09')
VERSION_HOUR = int('17')
VERSION_MINUTE = int('01')
MAJOR_VERSION = 1
MINOR_VERSION = 7
PATCH_VERSION = 202202091701
version_date = '2022/02/09 17:01'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
