[tool.poetry]
name = "defectio"
version = "0.2.3a"
description = "Wrapper for Revolt API"
authors = ["Leon Bowie <leon@bowie-co.nz>"]
license = "MIT"
documentation = "https://defectio.readthedocs.io"
homepage = "https://github.com/Darkflame72/defectio"
readme = "README.md"
repository = "https://github.com/Darkflame72/defectio"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Natural Language :: English",
  "Framework :: AsyncIO",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
  "Programming Language :: Python :: 3.9",
]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.4"
ulid-py = "^1.1.0"
orjson = "^3.6.3"
msgpack = "^1.0.2"
aiofiles = ">=0.7,<0.9"

[tool.poetry.dev-dependencies]
black = "^22.1"
mypy = "^0.931"
flake8 = "^4.0.1"
nox = "^2022.1.7"
darglint = "^1.8.1"
nox-poetry = "^0.9.0"
coverage = {extras = ["toml"], version = "^6.3"}
pytest = "^7.0.1"
pytest-asyncio = "^0.18.1"
Sphinx = "^4.4.0"
sphinxcontrib-trio = "^1.1.2"
pep8-naming = "^0.12.1"
Pygments = "^2.11.2"
flake8-annotations = "^2.7.0"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.4"
flake8-bugbear = "^22.1.11"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
pre-commit = "^2.17.0"
pre-commit-hooks = "^4.1.0"
safety = "^1.10.3"
reorder-python-imports = "^2.7.1"
aioresponses = "^0.7.3"
furo = "^2022.1.2"
sphinxext-opengraph = "^0.5.1"
sphinx-copybutton = "^0.5.0"
sphinx-autobuild = "^2021.3.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
