[tool.poetry]
name = "clointfusion"
version = "1.1.7"
description = "Python based Automation (RPA) Platform"
authors = ["Clointfusion <clointfusion@cloint.com>"]
exclude = ["clointfusion/resources/data.json",]
license = "BSD"
readme = "README.md"
homepage = "https://github.com/ClointFusion/ClointFusion"
repository = "https://github.com/ClointFusion/ClointFusion"
documentation = "https://clointfusion.readthedocs.io/"
keywords = ["ClointFusion","RPA","Python","Automation","BOT","Software BOT","ROBOT","Dost"]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Intended Audience :: Developers',      
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: BSD License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Framework :: Robot Framework',
    'Programming Language :: Python',
]

[tool.poetry.urls]
'Date ❤️ with ClointFusion' = 'https://sites.google.com/view/clointfusion-hackathon/date-with-clointfusion'
'WhatsApp Community' = 'https://chat.whatsapp.com/JKr7m0avmkIFwYgMarShZG'
'Hackathon Website' = 'https://tinyurl.com/ClointFusion'
'Documentation' = 'https://clointfusion.readthedocs.io'
'Bug Reports' = 'https://github.com/ClointFusion/ClointFusion/issues'
'Windows EXE' = 'https://github.com/ClointFusion/ClointFusion/releases/download/v1.0.0/ClointFusion_Community_Edition.exe'
'Medium' = 'https://medium.com/@clointfusion/bd152f4a1e0d?source=friends_link&sk=25b6051d75a8a4bb3e9a3e1a46516766'

[tool.poetry.dependencies]
python = "^3.7.1"
PyAutoGUI = "^0.9.53"
clipboard = "^0.0.4"
PySimpleGUI = "^4.55.1"
emoji = "^1.6.1"
matplotlib = "^3.5.1"
openpyxl = "^3.0.9"
pandas = "^1.3.5"
requests = "^2.26.0"
cryptocode = "^0.1"
xlsx2html = "^0.4.0"
pyfiglet = "^0.8.post1"
xls2xlsx = "^0.1.5"
xlwt = "^1.3.0"
webdriver-manager = "^3.5.2"
click = "^8.0.3"
pyinspect = "^0.1.0"
speedtest-cli = "^2.1.3"
rich = "^10.16.1"
SpeechRecognition = "^3.8.1"
pyttsx3 = "^2.90"
win10toast-click = "^0.1.2"
helium = "^3.0.8"
colored = "^1.4.3"

[tool.poetry.scripts]
cf = "clointfusion.cli.cf:main"
cf_st = "clointfusion.cli.st:main"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
