[tool.poetry]
name = "cfm_id"
version = "0.1.7"
description = "A Python wrapper to use CFM-ID : https://cfmid.wishartlab.com"
authors = ["Yann Beauxis <dev@yannbeauxis.net>"]
license = "LGPL-2.1-only"
readme = "README.md"
homepage = "https://gitlab.com/metwork/libs/cfm-id"
repository = "https://gitlab.com/metwork/libs/cfm-id"

[tool.poetry.dependencies]
python = "^3.7.1"
matchms = "^0.13.0"
pandas = "^1.3.4"
llvmlite = "^0.34.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
black = "^21.5b2"
rope = "^0.19.0"
pylint = "^2.8.3"
flake8 = "^4.0.1"
mypy = "^0.910"
pytest-datadir = "^1.3.1"
types-setuptools = "^57.4.2"
pytest-cov = "^3.0.0"
pytest-subprocess = "^1.2.0"

[tool.poetry.scripts]
test = "tests.cli:run"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
