[package]
authors = ["Jérome Eertmans <jeertmans@icloud.com>"]
name = "ropey"
version = "0.0.3-alpha"
edition = "2018"
description = "Python bindings for Rust's Ropey library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ropey"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
ropey = "1.3.2"
