[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "ropey"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
description = "Python bindings for Rust's Ropey library."
readme = "README.md"
maintainers = [
    {name = "Jérome Eertmans", email = "jeertmans@icloud.com"}
]
license = {file = "LICENSE.md"}
