[tool.poetry]
name = "py-namethatcolor"
version = "0.1.0"
description = "A small tool to get the closest known color to any given one and also generates its general shade (like Blue, Red, Black, etc)"
license = "MIT"
readme = "README.rst"
authors = ["Mikhail Porokhovnichenko <marazmiki@gmail.com>"]
homepage = "https://github.com/marazmiki/py-namethatcolor"
repository = "https://github.com/marazmiki/py-namethatcolor"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7"
isort = "^5.10.1"
black = "^22.1.0"
pre-commit = "^2.17.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
py_version=310
profile = "black"
src_paths = ["src", "tests"]
line_length=79
atomic = true
