
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-11T19:49:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7872e9f317516f842b9d03f6adde3a74267d1eb",
 "version": "0.0.62.post0.dev239"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
