[tool.poetry]
name = "melter"
version = "0.6.3"
description = "Identifies unsolved cases that should be analyzed again"
authors = ["Henning Onsbring <henning.onsbring@scilifelab.se>"]
readme = "README.md"

[tool.poetry.scripts]
melter = "melter.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4.0"}
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
