[tool.poetry]
name = "hypermodern-python-mikeh"
version = "0.1.0"
description = "Hypermodern Python Project"
authors = ["MichaelHarrison87 <harrisoneighty7@gmail.com>"]
license = "GNU GPL 3.0"
readme = "README.md"
homepage = "https://github.com/MichaelHarrison87/hypermodern-mikeh"
repository = "https://github.com/MichaelHarrison87/hypermodern-mikeh"
keywords = ["hypermodern"]
packages = [
    { include = "hypermodern_python", from = "src" }
]

[tool.poetry.scripts]
hypermodern-python="hypermodern_python.console:main"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.3"
requests = "^2.27.1"
desert = "^2020.11.18"
marshmallow = "^3.14.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
coverage = {extras = ["toml"], version = "^6.3.1"}
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
nox = "^2022.1.7"
black = "^22.1.0"
flake8 = "^4.0.1"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.4"
flake8-bugbear = "^22.1.11"
flake8-import-order = "^0.18.1"
safety = "^1.10.3"
mypy = "^0.931"
typeguard = "^2.13.3"
flake8-annotations = "^2.7.0"
flake8-docstrings = "^1.6.0"
darglint = "^1.8.1"
xdoctest = "^0.15.10"
Pygments = "^2.11.2"
sphinx-autodoc-typehints = "^1.17.0"
codecov = "^2.1.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["hypermodern_python"]

[tool.coverage.report]
show_missing = true
