[tool.poetry]
name = "fa_purity"
version = "1.1.2"
description = "Pure functional and typing utilities"
authors = ["Product Team <development@fluidattacks.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Deprecated = "^1.2.12"
more-itertools = "^8.10.0"
simplejson = "^3.17.6"
types-simplejson = "^3.17.2"
types-Deprecated = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic=true
combine_as_imports=true
force_alphabetical_sort=true
force_grid_wrap=1
force_sort_within_sections=true
include_trailing_comma=true
remove_redundant_aliases=true
skip_gitignore=true
use_parentheses=true
multi_line_output=3

[tool.black]
line-length = 79
target-version = ['py38']
