name: Install with flit and test via Pytest

on:
  push:
    paths:
    - '**.py' # only run workflow when source files changed 
    - '**.yml'
    - 'requirements.txt'
    - 'pyproject.toml'

jobs:
  linux-pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: true
      matrix:
         python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Check Black code style
      uses: psf/black@stable #https://black.readthedocs.io/en/stable/integrations/github_actions.html
    
    - name: Upgrade pip
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install flit torch
        pip install numba==0.53.* numpy==1.22.0
        # pip install psutil==5.8.0 virtualenv==20.11.0 Pygments==2.11.1 zipp==3.6.0 jsonschema==4.3.2 attrs==21.3.0
        # pip install oldest-supported-numpy # might need to go into pyproject.toml requires instead
        # pip install torch==1.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
        # flit install --deps production --extras test
        flit install
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export NUMBA_ENABLE_CUDASIM="1"
        python -m pytest
        
#     - name: publish-to-conda # requires setup.py file
#       uses: fcakyon/conda-publish-action@v1.3
#       with:
#         subdir: 'conda'
#         anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
#         platforms: 'win osx linux'

#       with:
#         submodules: recursive
