[tool.poetry]
name = "fxh-my-app"
version = "2.4.0"
description = ""
authors = ["juntao <61410813@qq.com>"]

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.5.3"
redis = "^3.5.3"
pymongo = {extras = ["srv"], version = "^4.0.1"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
