# ci:
#     skip: [mypy]
default_language_version:
    python: python3
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: check-docstring-first
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        types: [python]
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.76'
    hooks:
      - id: flynt
        language: python
        types: [python]
        args: [--line-length, '999', --aggressive, --fail-on-change]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 0.11.0
    hooks:
      - id: flakeheaven
#  - repo: local
#    # We do not use pre-commit/mirrors-mypy,
#    # as it comes with opinionated defaults
#    # (like --ignore-missing-imports)
#    # and is difficult to configure to run
#    # with the dependencies correctly installed.
#    hooks:
#      - id: mypy
#        name: mypy
#        entry: "bash ./build-scripts/run-mypy"
#        language: system
#        types: [python]
#        # use require_serial so that script
#        # is only called once per commit
#        require_serial: true
#        # Print the number of files as a sanity-check
#        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
