name: Build docs

on:
  release:
    types: [published]

jobs:
  build-docs:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[docs]
    - name: Update Sphinx docs
      run: |
        sphinx-build -E -b html docs docs/_build/html
        touch docs/_build/html/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: docs/_build/html
