VERSION_YEAR = 2022
VERSION_MONTH = int('02')
VERSION_DAY = int('09')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('55')
MAJOR_VERSION = 1
MINOR_VERSION = 7
PATCH_VERSION = 202202091655
version_date = '2022/02/09 16:55'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
