[tool.poetry]
name = "baguette_bi"
version = "0.1.11"
description = ""
authors = ["Mikhail Akimov <rovinj.akimov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.65.1"
SQLAlchemy = "^1.4.15"
typer = "^0.4.0"
itsdangerous = "^2.0.1"
Jinja2 = "^3.0.1"
altair = "^4.1.0"
vega-datasets = "^0.9.0"
uvicorn = "^0.17.4"
aiofiles = "^0.7.0"
psycopg2-binary = "^2.8.6"
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
WTForms = "^2.3.3"
python-multipart = "^0.0.5"
python-dotenv = "^0.17.1"
Markdown = "^3.3.4"
Babel = "^2.9.1"
alembic = "^1.6.5"
Pygments = "^2.9.0"
gunicorn = "^20.1.0"
uvloop = "^0.15.2"
httptools = "^0.2.0"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.5b1"
flake8 = "^3.9.2"
isort = "^5.8.0"
pytest-cov = { extras = ["toml"], version = "^2.12.1" }

[tool.poetry.scripts]
baguette = "baguette_bi.cli:app"

[tool.pytest.ini_options]
addopts = "--cov-report xml --cov-report html --cov=baguette_bi"

[tool.coverage.run]
omit = ["baguette_bi/examples/**.py"]

[tool.isort]
profile = "black"
known_first_party = ["baguette_bi"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
