[tool.poetry]
name = "odeo-python-sdk"
version = "0.0.1"
description = "Python library for Odeo For Business API"
license = "MIT"
authors = ["Rudi <rudi@odeo.co.id>"]
readme = "README.md"
homepage = "https://docs.odeo.co.id"
repository = "https://github.com/odeoteknologi/odeo-python-sdk"
documentation = "https://odeo-python-sdk.readthedocs.io"
packages = [{ include = "odeo" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
requests-oauthlib = "^1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
requests-mock = "^1.9.3"
freezegun = "^1.1.0"
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
