[tool.poetry]
name = "my-stocks"
version = "0.1.0"
description = ""
authors = ["markus <datamastery87@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
my-stocks = "my_stocks.main:app"

[tool.poetry.dependencies]
python = ">=3.7 <3.10"
yfinance = "^0.1.70"
typer = "^0.4.0"
matplotlib = "^3.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
