[tool.poetry]
name = "zxc"
version = "0.0.1"
description = "1000-7 calculyator"
authors = ["fikko"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
