[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "vocles"
authors = [
    {name = "David Nicholson", email = "nickledave@users.noreply.github.com"}
]
description = "a lightweight tool for building datasets of vocalizations"
version = "0.1.0"
classifiers = [
        'License :: OSI Approved :: BSD License',
        'Development Status :: 5 - Production/Stable',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: Implementation :: CPython'
]
requires-python = ">=3.7"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "attrs >=21.4.0",
    "pandas >=1.3.5",
]

[project.urls]
Home = "https://github.com/NickleDave/vocles"

[project.optional-dependencies]
dev = [
    "twine >=3.7.1",
    "black >=21.12b0",
    "ipython >=8.0.0",
    "nox >= 2022.1.7",
]
test = [
    "pytest >=6.2.5",
    "pytest-cov >=2.11.1",
]
doc = [
    "sphinx >=4.4.0"
]
