[tool.poetry]
name = "nonebot-bison"
version = "0.4.4"
description = "Subscribe message from social medias"
authors = ["felinae98 <felinae225@qq.com>"]
license = "MIT"
homepage = "https://github.com/felinae98/nonebot-bison"
keywords = ["nonebot", "nonebot2", "qqbot"]
readme = "README.md"
packages = [
    { include = "nonebot_bison", from = "./src/plugins/" }
]
include = [
    "src/plugins/nonebot_bison/admin_page/dist/**/*"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: MIT License"
]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "2.0.0-alpha.16"
httpx = ">=0.16.1 <1.0.0"
bs4 = "^0.0.1"
tinydb = "^4.3.0"
feedparser = "^6.0.2"
pillow = "^8.1.0"
nonebot-adapter-cqhttp = "2.0.0-alpha.16"
apscheduler = "^3.7.0"
expiringdict = "^1.2.1"
pyjwt = "^2.1.0"
aiofiles = "^0.7.0"
python-socketio = "^5.4.0"
playwright = "^1.17.2"
nonebot-plugin-help = "^0.1.5"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.4"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
respx = "^0.19.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
markers = [
    "compare: compare fetching result with rsshub",
    "render: render img by chrome"
]
