[tool.poetry]
name = "neclib"
version = "0.1.0"
description = "Pure Python tools for NECST."
license = "MIT"
readme = "README.md"
authors = ["KaoruNishikawa <k.nishikawa@a.phys.nagoya-u.ac.jp>"]
homepage = "https://github.com/nanten2/neclib"
repository = "https://github.com/nanten2/neclib"

[tool.poetry.dependencies]
python = ">=3.6, <3.10"
importlib-metadata = { version = "^4.4", python = "<3.8" }
numpy = "^1.19"
typing-extensions = { version = "^4.0", python = "<3.8" }

[tool.poetry.dev-dependencies]
black = "^20.6b"
flake8 = "^3.8"
ipykernel = "^5.3"
m2r2 = "^0.3"
numpydoc = "^1.0"
pydata-sphinx-theme = "^0.7.2"
pytest = "^5.2"
sphinx = "^4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
