
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-16T11:21:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "22d334e4635d9ba5c383b0da5b1e8ec24aaf4660",
 "version": "0.7.1.post.dev385"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
