[tool.poetry]
name = "spice_kernels"
version = "0.1.7"
description = ""
authors = ["Steve Guest <steve.guest@stfc.ac.uk>"]
repository = "https://test.pypi.org/project/spice-kernels/"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.20"
astropy = "^4.3"
matplotlib = "^3.4"
scipy = "^1.6"
cmapy = "^0.6"
spiceypy = "^4.0.2"
opencv-python = "^4.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
get_pointing = "spice_kernels.spice_kernels:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
