[tool.poetry]
name = "ServantReasoning"
version = "0.2.0"
description = "一个基于Nonebot2的游戏插件"
license = "MIT"
authors = "suhexia"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0-b1"
nonebot-adapter-onebot = "^2.0.0-b1"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"