[tool.poetry]
name = "airflow-providers-prima"
version = "0.0.1"
description = "python repository for commmons operators,hooks and utils for Apache Airflow"
authors = ["sceriol <simone.cerioli@prima.it>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
