[build-dependencies]
proc-macro2 = "1.0"
quote = "1.0"

[build-dependencies.rand]
version = "0.8"

[build-dependencies.syn]
features = ["full", "visit"]
version = "1.0"

[dependencies]
nalgebra = "0.30"
thiserror = "1.0"

[dependencies.bincode]
optional = true
version = "1.3"

[dependencies.dyn-clone]
optional = true
version = "1.0"

[dependencies.ndarray]
version = "0.15"

[dependencies.num-complex]
version = "0.4"

[dependencies.qoqo_calculator]
version = "0.6"

[dependencies.rand]
version = "0.8.4"

[dependencies.rand_distr]
optional = true
version = "0.4"

[dependencies.roqoqo-derive]
path = "../roqoqo-derive"
version = "0.10"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.typetag]
optional = true
version = "0.1"

[dev-dependencies]
test-case = "1.1.0"

[dev-dependencies.serde_test]
version = "1.0"

[features]
default = ["serialize"]
dynamic = ["typetag", "dyn-clone"]
overrotate = ["rand_distr", "roqoqo-derive/overrotate"]
serialize = ["serde", "ndarray/serde", "num-complex/serde", "bincode"]

[lib]
doctest = false
name = "roqoqo"
path = "src/lib.rs"

[package]
authors = ["HQS Quantum Simulations <info@quantumsimulations.de>"]
categories = ["science", "simulation"]
description = "Rust Quantum Computing Toolkit by HQS"
documentation = "https://docs.rs/roqoqo/"
edition = "2021"
homepage = "https://github.com/HQSquantumsimulations/qoqo"
include = ["src*", "build.rs", "katex.html", "LICENSE", "README.md"]
license = "Apache-2.0"
name = "roqoqo"
readme = "../README.md"
repository = "https://github.com/HQSquantumsimulations/qoqo"
rust-version = "1.56"
version = "0.10.0"
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex.html", "--document-private-items"]
