# coding: utf-8

"""
    BAPP API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.inline_response20057_balances import InlineResponse20057Balances  # noqa: E501
from bapp_api_client.rest import ApiException


class TestInlineResponse20057Balances(unittest.TestCase):
    """InlineResponse20057Balances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20057Balances(self):
        """Test InlineResponse20057Balances"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.inline_response20057_balances.InlineResponse20057Balances()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
