[tool.poetry]
name = "mmf-meta"
version = "0.1.10b0"
description = ""
authors = ["Викторов Андрей Германович <andvikt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"

[tool.poetry.dev-dependencies]

pandas = "^1.4.0"
openpyxl = "^3.0.9"
xlrd = "^2.0.1"
opencv-python = "^4.5.5"
PyTurboJPEG = "^1.6.5"
XlsxWriter = "^3.0.2"
bump2version = "^1.0.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mmfmeta = 'mmf_meta:cli'

[tool.poetry.urls]
homepage = 'https://github.com/mm-framework/mmf-meta'
documentation = 'https://mm-framework.github.io/docs/'