
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-09T16:26:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a55ccf5e42304a159c34ce6a0a5e8ba69a5f343f",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
