codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        enabled: no
        if_not_found: success

comment: false
