[tool.poetry]
name = "not_very_useful_animal"
version = "1.0.0"
description = "a not very useful animal"
authors = ["Fatemejahanni"]
packages = [
    { include = "*.py" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
