[tool.poetry]
name = "lawsql-cases-raw"
version = "0.0.1"
description = "Get decision data from .html and yaml files; updates local database with field lookups."
authors = ["Marcelino G. Veloso III <mars@veloso.one>"]

[tool.poetry.dependencies]
python = "^3.9"
citation-docket = "^0.0.1"
citation-report = "^0.0.1"
lawsql-cases-justices = "^0.0.1"
Unidecode = "^1.3.0"
sqlite-utils = "^3.22"
datasette = "^0.60.1"
httpx = "^0.22.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.12.1"
mypy = "^0.930"
black = "^22.1"
isort = "^5.10.1"
pre-commit = "^2.17.0"
ipykernel = "^6.7.0"
tqdm = "^4.62"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --doctest-modules --cov=lawsql_cases_raw tests/"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.1.12"]
build-backend = "poetry.core.masonry.api"
