
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-09T16:14:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed46cf33d59ed03f65640733f008a2e6328778fe",
 "version": "1.0.0-rc.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
