
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-11T10:36:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "50b5867a1ee56fbd6be9ccdde01fb39f8a38f013",
 "version": "1.96.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
