[tool.poetry]
name = "pypi-publish-amash"
version = "0.1"
description = "Empty package to test the GitHub Action `coveooss/pypi-publish-with-poetry`"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/iaanimashaun/pypi-publish.git"
authors = ["Jonathan Piché <tools@coveo.com>"]


[tool.poetry.dependencies]
python = ">=3.8"


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
