[tool.poetry]
name = "bgenv"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.2"
pandas = "^1.4.1"
geopandas = "^0.10.2"
networkx = "2.6.2"
igraph = "^0.9.9"
Shapely = "^1.8.0"
folium = "^0.12.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
