[tool.poetry]
name = "redlines"
version = "0.2.0"
description = ""
authors = ["houfu <houfu@lovelawrobots.com>"]

[tool.poetry.dependencies]
python = "^3.10 "

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-sugar = "^0.9.4"
pytest-cov = "^3.0.0"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
