from TkWebPage import*
def IE():
    IE = IE(["baidu","pypi","game","bilibili"])
    IE.url("baidu","http://www.baidu.com")
    IE.url("pypi","http://pypi.org")
    IE.url("game","http://chromedino.com")
    IE.url("bilibili","http://www.bilibili.com")
    IE.title("baidu","baidu")
    IE.title("pypi","pypi")
    IE.title("game","game")
    IE.title("bilibili","bilibili")
    IE.run("baidu")
    IE.run("pypi")
    IE.run("game")
    IE.run("bilibili")
def HTML():
    HTML = HTML("html")
    HTML.title("html","HTML")
    HTML.run("html")
def Chromium():
    C = Chrome(["baidu","pypi","game","bilibili"])
    C.url("baidu","www.baidu.com")
    C.url("pypi","pypi.org")
    C.url("game","chromedino.com")
    C.url("bilibili","www.bilibili.com")
    C.title("baidu","baidu")
    C.title("pypi","pypi")
    C.title("game","game")
    C.title("bilibili","bilibili")
    C.run("baidu")
    C.run("pypi")
    C.run("game")
    C.run("bilibili")
if __name__ == "__main__":
    IE()
    HTML()
    Chromium()
