[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
classifiers = ["Topic :: Software Development :: Build Tools"]
description = "Tool to handle multiple beamer decks."
homepage = "https://github.com/mlambda/deckz"
license = "Apache-2.0"
name = "deckz"
readme = "README.md"
version = "18.1.1"

[tool.poetry.dependencies]
Jinja2 = "^2.11.3"
PyYAML = "^5.4.1"
appdirs = "^1.4.4"
attrs = "^21.2.0"
email-validator = "^1.1.3"
google-api-python-client = "^2.3.0"
google-auth-oauthlib = "^0.4.4"
matplotlib = ">= 3, < 4"
pydantic = "^1.8.1"
pygit2 = "^1.5.0"
python = "^3.8"
rich = "^10.1.0"
sendgrid = "^6.7.0"
typer = {version = "^0.3.2", extras = ["all"]}
watchdog = "^2.1.1"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
flake8 = "^3.9.2"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
isort = "^5.9.1"
mypy = "^0.812"
"pdfminer.six" = "^20201018"
pylint = "^2.8.2"
pytest = "^6.2.4"
pytest-cov = "^2.11.1"

[tool.poetry.scripts]
deckz = 'deckz.cli:main'

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
