[tool.poetry]
name = "unigo"
version = "2.0.3"
description = ""
authors = ["glaunay <pitooon@gmail.com>"]
license = "BSD"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
requires = "^0.10.2"
Owlready2 = "^0.36"
scipy = "^1.8.0"
docopt = "^0.6.2"
marshmallow = "^3.14.1"
Flask = "^2.0.2"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
