
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-14T17:13:20+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "4958551b597439090616b597ff8bd2234373a3ac",
 "version": "1.36.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
