[tool.poetry]
name = "yarender"
version = "0.1.4"
description = ""
authors = ["DeDA <denis.deryabin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
rich = "^11.2.0"
click = "^8.0.3"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
yarender = "yarender.main:render"
