[tool.poetry]
name = "neuralspace"
version = "0.1.0"
description = "A Python CLI for NeuralSpace APIs"
authors = ["Ayushman Dash <ayushman@neuralspace.ai>"]


[tool.poetry.dependencies]
python = ">=3.7.1,<3.9"
click = "^8.0.1"
randomname = "^0.1.3"
prettytable = "^2.1.0"
rich = "^10.7.0"
coloredlogs = "~=14"
rasa = "^2.8.12"
pandas = "1.3.3"
PyYAML = "^6.0"
keras = "2.6"
urllib3 = "~=1.26.5"
twine = "^3.7.1"
datasets = "^1.18.3"

[tool.poetry.dev-dependencies]
isort = "^4.3.21"
flake8 = "^3.7.9"
pytest = "^5.4.1"
coverage = "^5.1"
requirements-parser = "^0.2.0"
pytest-xdist = "^1.32.0"
black = "^20.8b1"
twine = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
