name: Build Docs
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/zh/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - name: Build Docs
        run: |
          cd ./docs/zh
          mkdocs gh-deploy --force

