[tool.poetry]
name = "beetcamp"
version = "0.12.0"
description = "Bandcamp autotagger source for beets (http://beets.io)."
authors = ["Šarūnas Nejus <snejus@pm.me>"]
readme = "README.md"
license = "GPL-2.0"
homepage = "https://github.com/snejus/beetcamp"
repository = "https://github.com/snejus/beetcamp"

packages = [{ include = "beetsplug" }]
include = ["LICENSE", "README.md"]

[tool.poetry.dependencies]
python = ">=3.6,<3.10"

requests = "*"
cached-property = "^1.5.2"
pycountry = "^20.7.3"
python-dateutil = "^2.8.2"
beets = "*"
rich = "*"

[tool.poetry.dev-dependencies]
dataclasses = { version = "*", python = "<3.7" }
flake8 = ">=3.8.4"
flake8-bandit = ">=2.0.0"
mypy = ">=0.790"
pylint = ">=2.7.4"
pytest = ">=6.2"
pytest-cov = ">=2.10.1"
pytest-randomly = "*"
pytest-lazy-fixture = ">=0.6.3"
tox = ">=3.21.1"
types-setuptools = "^57.0.0"
types-requests = "^2.25.0"
types-six = "^0.1.7"
types-python-dateutil = "^2.8.2"
pytest-clarity = "^1.0.1"

[tool.poetry.scripts]
beetcamp = "beetsplug.bandcamp:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
