[tool.poetry]
name = "dilivia-data-client"
version = "0.1.1"
description = ""
authors = ["dilivia.enovea <contact@dilivia.net>"]
maintainers = ["martin.nivon <martin.nivon@enovea.net>"]
homepage = "https://www.dilivia.net/"
documentation = "https://www.dilivia.net/posts/" # mettre article "utilisation librairie" quand il sera vraiment déployé

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pydruid = "^0.6.2"
requests = "^2.27.1"
numpy = "^1.22.1"
pytz = "^2021.3"
python-dateutil = "^2.8.2"
pandas = "1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
coverage = "^6.3"
taskipy = "^1.9.0"
isort = "^5.10.1"
pre-commit = "^2.17.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
