
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-09T12:57:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec1869147e55a686e22a2653bc7a616773d10e27",
 "version": "v0.5.0a.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
