[tool.poetry]
name = "macro_counter"
version = "0.2.0"
description = "Python macro nutrient counter."
authors = ["Laurent Arthur <laurent.arthur75@gmail.com>"]
license = "GPLv3"
readme = "README.md"
homepage = "https://github.com/ludwig778/macro_counter"
repository = "https://github.com/ludwig778/macro_counter"
classifiers = [
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
prompt-toolkit = "^3.0.18"
tabulate = "^0.8.9"
pymongo = "^3.11.4"
pyparsing = "^2.4.7"
dnspython = "^2.1.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
isort = "^5.8.0"
piprot = "^0.9.11"
pytest = "^6.2.4"
ipython = "^7.23.1"
pytest-cov = "^2.11.1"
pytest-env = "^0.6.2"
mypy = "^0.931"
types-tabulate = "^0.8.5"
black = "^22.1.0"

[tool.poetry.scripts]
macro_counter = "macro_counter:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
