# coding: utf-8

"""
    BAPP API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.api.simple_stocks_api import SimpleStocksApi  # noqa: E501
from bapp_api_client.rest import ApiException


class TestSimpleStocksApi(unittest.TestCase):
    """SimpleStocksApi unit test stubs"""

    def setUp(self):
        self.api = bapp_api_client.api.simple_stocks_api.SimpleStocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_simple_stocks_real_time_stock_list(self):
        """Test case for simple_stocks_real_time_stock_list

        """
        pass

    def test_simple_stocks_real_time_stock_read(self):
        """Test case for simple_stocks_real_time_stock_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
