[tool.poetry]
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: AsyncIO",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Internet :: WWW/HTTP",
]
description = "REST API Client designed for microservices"
homepage = "https://github.com/mardiros/blacksmith"
license = "BSD-derived"
name = "blacksmith"

readme = "README.rst"
repository = "https://github.com/mardiros/blacksmith"
version = "1.0.0"

[tool.poetry.dependencies]
aioredis = {version = "^2.0.0", optional = true}
httpx = "^0.21.1"
prometheus-client = {version = "^0.13.0", optional = true}
pydantic = "^1.8.2"
python = "^3.7"
typing-extensions = "^4.0.1"
purgatory-circuitbreaker = "^0.7.2"

[tool.poetry.extras]
http_cache_async = ["aioredis"]
http_cache_sync = ["redis"]
prometheus = ["prometheus-client"]

[tool.poetry.dev-dependencies]
Sphinx = "^4.2.0"
aioredis = {version = "^2.0.0"}
black = "^22.1.0"
coverage = {version = "^6.2", extras = ["toml"]}
fastapi = "^0.73.0"
isort = "^5.9.3"
prometheus-client = "^0.13.0"
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
sphinx-rtd-theme = "^1.0.0"
tomlkit = "^0.7.2"
uvicorn = "^0.15.0"
flake8 = "^4.0.1"
unasync = "^0.5.0"
starlette-zipkin = "^0.2.0"
redis = "^4.1.0"
esbonio = "^0.8.0"
mypy = "^0.931"
types-setuptools = "^57.4.7"
types-redis = "^4.1.8"

[tool.pytest.ini_options]
norecursedirs = "tests/unittests/scanned_resources"

[tool.pyright]
include = ["src", "tests"]
ignore = ["examples"]
typeCheckingMode = "strict"
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportPrivateUsage = false

[[tool.mypy.overrides]]
module = "blacksmith.*"
disallow_untyped_defs = true
disallow_any_generics = true

[tool.isort]
profile = "black"

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "except ImportError:",
  "except pkg_resources.DistributionNotFound:",
  "\\s+\\.\\.\\.$",
  "# coverage-ignore",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
