
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-10T10:44:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8ac28bd304fae4c4aa143780191532f10b12b3e",
 "version": "2595"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
