[tool.poetry]
name = "pycfdi_credentials"
version = "0.1.0"
description = "Library to manage CSD and FIEL files from SAT. Use this to sign, verify and get certificate data."
authors = ["Moises Navarro <moisalejandro@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyOpenSSL = "^22.0.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
coverage = "^6.3.1"
isort = "^5.10.1"
mypy = "^0.931"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
hypothesis = "^6.36.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
