[tool.poetry]
name = "Arguebuf"
version = "0.2.14"
description = "A library for loading argument graphs in various formats (e.g., AIF)."
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "http://recap.uni-trier.de"
repository = "https://github.com/ReCAP-UTR/Arguebuf"
documentation = "https://arguebuf.readthedocs.io/en/latest"

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.4"
pendulum = "^2.0"
graphviz = "^0.13.2"
lxml = "^4.6"
sphinx = { version = "^3.5", optional = true }
sphinx-rtd-theme = { version = "^0.5.2", optional = true }
furo = { version = "^2021.4.11b34", optional = true }
myst-parser = { version = "^0.13.7", optional = true }
arg-services = "^0.1.18"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-datadir = "^1.3.1"
deepdiff = { extras = ["murmur"], version = "^4.0.9" }
pytest-cov = "^3.0.0"

[tool.poetry.extras]
docs = ["sphinx", "furo", "sphinx-rtd-theme", "myst-parser"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
