[tool.poetry]
name = "wire_web"
version = "0.3.2"
description = "Wire the web"
authors = ["Leo B. <bernerdoodle@outlook.de>"]
keywords = ["asgi", "python", "web", "webdevelopment"]
readme = "readme.md"
license = "MIT"
homepage = "https://wire.bernerdev.de/"
repository = "https://github.com/cheetahbyte/wire"
include = [
    "LICENSE"
]
packages = [
    {include = "wire"}
]


[tool.poetry.dependencies]
python = "^3.9"
multidict = "^5.1.0"
wire-fuchs = "^0.1.0"

wire-rxtr = "^0.2"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.8b0"
pdoc3 = "^0.10.0"
commitizen = "^2.20.3"
uvicorn = "^0.17.1"

[tool.poetry.scripts]
run = ""
[tool.poetry.urls]
Chat = "https://discord.gg/EtqGfBVuZS"
Changes = "https://wire.bernerdev.de/changelog"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
