---
version: 1
disable_existing_loggers: false
#propagate: true
formatters:
    simple:
        format: '%(asctime)s %(name)-20s %(levelname)-8s %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    file:
        level: INFO
        class : logging.handlers.RotatingFileHandler
        formatter: simple
        filename: /var/log/snooze/snooze-server.log
        maxBytes: 1024000
        backupCount: 5
loggers:
    snooze:
        level: INFO
        handlers: [console, file]
        propagate: false
