
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-11T12:07:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4d85a344ef38024eb47c7daaa557d4fe17730ff",
 "version": "1.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
