
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-14T20:55:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f43ca319e49e8df5636e8c476929a7cd6d33590",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
