
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-09T22:35:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "916cf9bc37e7e01824de23b5c343fa648d6c6731",
 "version": "1.0.2.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
