[tool.poetry]
name = "masureel"
version = "0.1.3"
description = ""
authors = ["Lucas Selfslagh <lucas.selfslagh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
masureel = "masureel.console:main"