[tool.poetry]
name = "core_dev"
version = "0.2.0"
description = ""
authors = ["alexzanderr <alexxander18360@gmail.com>"]
packages = [
    # this must be the same as package name to work
	{ include = "core_dev" },
]
# not working
# ------------------------------
# include = [
# 	"coverage/coverage.svg",
# 	"coverage/badge.svg",
# 	"coverage/docs.svg",
# ]
license = "MIT"
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "Framework :: Flake8",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
homepage = "https://github.com/alexzanderr/_core-dev"
repository = "https://github.com/alexzanderr/_core-dev"


[tool.poetry.dependencies]
python = "^3.10"
appdirs = "^1.4.4"
astroid = "^2.9.3"
async_generator = "^1.10"
attrs = "^21.4.0"
beautifulsoup4 = "^4.10.0"
bs4 = "^0.0.1"
certifi = "^2021.10.8"
cffi = "^1.15.0"
chardet = "^4.0.0"
charset-normalizer = "^2.0.11"
click = "^8.0.3"
colorama = "^0.4.4"
commonmark = "^0.9.1"
coverage-badge = "^1.1.0"
coverage = "^6.3.1"
cryptography = "^36.0.1"
cycler = "^0.11.0"
datedelta = "^1.4"
decopatch = "^1.4.8"
decorator = "^5.1.1"
docstr-coverage = "^2.1.1"
execnet = "^1.9.0"
ffmpeg-python = "^0.2.0"
fonttools = "^4.29.1"
future = "^0.18.2"
geojson = "^2.5.0"
greenlet = "^1.1.2"
gTTS = "^2.2.3"
h11 = "^0.13.0"
idna = "^3.3"
imageio-ffmpeg = "^0.4.5"
imageio = "^2.15.0"
importlib-metadata = "^4.10.1"
iniconfig = "^1.1.1"
isort = "^5.10.1"
jedi = "^0.18.1"
keyboard = "^0.13.5"
kiwisolver = "^1.3.2"
lazy-object-proxy = "^1.7.1"
makefun = "^1.13.1"
matplotlib = "^3.5.1"
mccabe = "^0.7.0"
MouseInfo = "^0.1.3"
numpy = "^1.22.2"
opencv-python = "^4.5.5"
outcome = "^1.1.0"
packaging = "^21.3"
parso = "^0.8.3"
"pdfminer.six" = "^20211012"
pdfplumber = "^0.6.0"
Pillow = "^9.0.1"
platformdirs = "^2.4.1"
playsound = "^1.3.0"
playwright = "^1.18.2"
pluggy = "^1.0.0"
proglog = "^0.1.9"
prompt-toolkit = "^3.0.27"
ptpython = "^3.0.20"
py = "^1.11.0"
PyAudio = "^0.2.11"
PyAutoGUI = "^0.9.53"
pycparser = "^2.21"
pydub = "^0.25.1"
PyGetWindow = "^0.0.9"
Pygments = "^2.11.2"
PyMsgBox = "^1.0.9"
pyOpenSSL = "^22.0.0"
pyowm = "^3.2.0"
pyparsing = "^3.0.7"
PyPDF2 = "^1.26.0"
pyperclip = "^1.8.2"
pyppeteer = "^1.0.2"
PyRect = "^0.1.4"
PyScreeze = "^0.1.28"
PySocks = "^1.7.1"
pytesseract = "^0.3.8"
pytest-cases = "^3.6.8"
pytest-forked = "^1.4.0"
pytest-steps = "^1.8.0"
pytest-xdist = "^2.5.0"
pytest = "^7.0.0"
python-dateutil = "^2.8.2"
python-nmap = "^0.7.1"
python3-nmap = "^1.5.1"
python3-xlib = "^0.15"
pyttsx3 = "^2.90"
pytweening = "^1.0.4"
pytz = "^2021.3"
PyYAML = "^6.0"
pyzbar = "^0.1.8"
requests = "^2.27.1"
rich = "^11.1.0"
selenium = "^4.1.0"
setuptools = "^60.8.1"
simplejson = "^3.17.6"
six = "^1.16.0"
sniffio = "^1.2.0"
sortedcontainers = "^2.4.0"
sounddevice = "^0.4.4"
soupsieve = "^2.3.1"
SpeechRecognition = "^3.8.1"
stackprinter = "^0.2.5"
sudo = "^1.0.0"
toml = "^0.10.2"
tqdm = "^4.62.3"
trio-websocket = "^0.9.2"
trio = "^0.19.0"
urllib3 = "^1.26.8"
Wand = "^0.6.7"
wcwidth = "^0.2.5"
websockets = "^10.1"
wrapt = "^1.13.3"
wsproto = "^1.0.0"
zipp = "^3.7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
