[tool.poetry]
name = "micropub"
version = "0.0.7"
description = "A library for writing Micropub servers and clients."
authors = ["Angelo Gladding <self@angelogladding.com>"]
license = "CC0-1.0"
readme = "README.md"

[tool.poetry.scripts]
micropub = "micropub.__main__:main"

[tool.poetry.dependencies]
python = "^3.9"
understory = "^0"
nltk = "^3.6.5"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.12.1"
radon = "^5.1.0"
understory = {path = "../understory"}
microformats = {path = "../microformats-python"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
